version: '3.7'

services:
  telegram-bot-api:
    platform: linux/x86_64
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_LOCAL: 1
    volumes:
      - ./mount/telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
    restart: always