version: '3.7'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: compose/bot_app/Dockerfile
    image: audiobot
    platform: linux/x86_64
    depends_on:
      - redis
      - telegram-bot-api
      - db
    env_file:
      - ./.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_URL: http://telegram-bot-api:8081/bot
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./mount/output:/app/output
      - ./mount/telegram-bot-api:/app/input
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.0
    hostname: redis
    restart: always
    volumes:
      - ./mount/redis-data:/data/
    env_file:
      - ./.env
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    container_name: worker
    hostname: worker
    image: audiobot
    platform: linux/x86_64
    entrypoint: celery
    command: "-A app.tasks worker --loglevel=INFO"
    volumes:
      - ./mount/output:/app/output
      - ./mount/telegram-bot-api:/app/input
    depends_on:
      - bot
      - redis
    env_file:
      - ./.env
    environment:
      API_URL: http://telegram-bot-api:8081/bot
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: unless-stopped

  telegram-bot-api:
    container_name: telegram-bot-api
    hostname: telegram-bot-api
    image: aiogram/telegram-bot-api:latest
    platform: linux/x86_64
    environment:
      TELEGRAM_LOCAL: 1
      TELEGRAM_VERBOSITY: 2
    volumes:
      - ./mount/telegram-bot-api:/var/lib/telegram-bot-api
      - ./mount/output:/var/lib/telegram-bot-api/output
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    restart: always

  db:
    container_name: db
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    ports:
      - "65432:5432"
    volumes:
      - ./mount/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./mount/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M