"""alter tg-id to bigint

Revision ID: 05543f5dc7aa
Revises: c79960974b4a
Create Date: 2022-08-14 01:44:13.954867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05543f5dc7aa'
down_revision = 'c79960974b4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
