"""

Revision ID: ab9a063dbb93
Revises: 615430247c0e
Create Date: 2022-09-01 20:18:59.104298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9a063dbb93'
down_revision = '615430247c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(), server_default='infinity', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_ends_at')
    # ### end Alembic commands ###
