"""

Revision ID: 615430247c0e
Revises: 05543f5dc7aa
Create Date: 2022-09-01 19:58:57.010734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '615430247c0e'
down_revision = '05543f5dc7aa'
branch_labels = None
depends_on = None


subscription_plan = postgresql.ENUM(
    'free',
    'limited',
    'max',
    name='subscription_plan'
)


def upgrade() -> None:
    subscription_plan.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', subscription_plan, server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_plan')
    subscription_plan.drop(op.get_bind())
    # ### end Alembic commands ###
