"""create_table_job_add_user_balance

Revision ID: 0b526ec5e1fe
Revises: 7a5026ea0560
Create Date: 2024-09-16 01:23:43.077197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b526ec5e1fe'
down_revision = '7a5026ea0560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('frozen_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('balance_seconds', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('frozen_balance', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frozen_balance')
    op.drop_column('users', 'balance_seconds')
    op.drop_table('jobs')
    # ### end Alembic commands ###
