"""add filepath and duration and success to Job

Revision ID: 1263663c9434
Revises: 0b526ec5e1fe
Create Date: 2024-09-30 02:12:17.308688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1263663c9434'
down_revision = '0b526ec5e1fe'
branch_labels = None
depends_on = None
top_up_seconds = 60 * 30  # 30 minutes


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'frozen_amount', new_column_name='audio_length_seconds')
    op.add_column('jobs', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('success', sa.Boolean(), nullable=True))
    op.drop_column('users', 'frozen_balance')
    # top up balance to all users
    op.execute(f"UPDATE users SET balance_seconds = {top_up_seconds} where balance_seconds < {top_up_seconds}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'audio_length_seconds', new_column_name='frozen_amount')
    op.drop_column('jobs', 'success')
    op.drop_column('jobs', 'file_path')
    op.add_column('users', sa.Column('frozen_balance', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
